export const en = {
  login: {
    title: 'Login',
    welcome: 'Welcome to Nalandavar Finance',
    companyName: 'Nalandavar Finance',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    loginButton: 'Login',
    loggingIn: 'Logging in...',
  },
  dashboard: {
    title: 'Dashboard',
    totalLoans: 'Total Loans',
    renewalsPending: 'Renewals Pending',
    auctionAlerts: 'Auction Alerts',
    recentLoans: 'Recent Loans',
    quickActions: 'Quick Actions',
    createLoan: 'New Loan',
    viewAllLoans: 'View All Loans',
    loanId: 'Loan ID',
    customerName: 'Customer Name',
    amount: 'Amount',
    date: 'Date',
    status: 'Status',
  },
  createLoan: {
    title: 'Create New Loan',
    customerDetails: 'Customer Details',
    goldItems: 'Gold Items',
    calculation: 'Calculation & Preview',
    next: 'Next',
    previous: 'Previous',
    submit: 'Submit',
    submitting: 'Submitting...',
    addGoldItem: 'Add Gold Item',
    itemName: 'Item Name',
    weight: 'Weight (grams)',
    purity: 'Purity (karat)',
    remove: 'Remove',
    goldRate: 'Today\'s Gold Rate (per gram)',
    totalWeight: 'Total Weight',
    estimatedValue: 'Estimated Value',
    loanEligibility: 'Loan Eligibility (75%)',
    generatePreview: 'Generate AI Preview',
    loanPreview: 'Loan Preview',
  },
  common: {
    logout: 'Logout',
    name: 'Name',
    phone: 'Phone Number',
    address: 'Address',
    active: 'Active',
    closed: 'Closed',
    auctioned: 'Auctioned',
  },
  sidebar: {
    dashboard: 'Dashboard',
    createLoan: 'New Loan',
    allLoans: 'All Loans',
    renewals: 'Renewals',
    repayments: 'Repayments',
    auctions: 'Auctions',
    closures: 'Closures',
    accounting: 'Accounting',
  },
  accounting: {
    title: 'Accounting',
    dayBook: 'Day Book',
    voucherEntries: 'Voucher Entries',
    trialBalance: 'Trial Balance',
    cashInHand: 'Cash in Hand',
    loansOutstanding: 'Loans Outstanding',
    todayReceipts: 'Today\'s Receipts',
    todayPayments: 'Today\'s Payments',
  }
};