export const ta = {
  login: {
    title: 'உள்நுழை',
    welcome: 'நல்லாண்டவர் ஃபைனான்ஸ்-க்கு வரவேற்கிறோம்',
    emailLabel: 'மின்னஞ்சல்',
    passwordLabel: 'கடவுச்சொல்',
    loginButton: 'உள்நுழையவும்',
    loggingIn: 'உள்நுழைகிறது...',
  },
  dashboard: {
    title: 'டாஷ்போர்டு',
    totalLoans: 'மொத்த கடன்கள்',
    renewalsPending: 'புதுப்பித்தல் நிலுவையில்',
    auctionAlerts: 'ஏல அறிவிப்புகள்',
    recentLoans: 'சமீபத்திய கடன்கள்',
    quickActions: 'விரைவான செயல்கள்',
    createLoan: 'புதிய கடன்',
    viewAllLoans: 'அனைத்து கடன்களையும் காண்க',
    loanId: 'கடன் ஐடி',
    customerName: 'வாடிக்கையாளர் பெயர்',
    amount: 'தொகை',
    date: 'தேதி',
    status: 'நிலை',
  },
  createLoan: {
    title: 'புதிய கடன் உருவாக்கவும்',
    customerDetails: 'வாடிக்கையாளர் விவரங்கள்',
    goldItems: 'தங்கப் பொருட்கள்',
    calculation: 'கணக்கீடு & மாதிரிக்காட்சி',
    next: 'அடுத்து',
    previous: 'முந்தைய',
    submit: 'சமர்ப்பிக்கவும்',
    submitting: 'சமர்ப்பிக்கிறது...',
    addGoldItem: 'தங்கப் பொருளைச் சேர்க்கவும்',
    itemName: 'பொருள் பெயர்',
    weight: 'எடை (கிராம்)',
    purity: 'தூய்மை (காரட்)',
    remove: 'நீக்கு',
    goldRate: 'இன்றைய தங்க விலை (கிராம்)',
    totalWeight: 'மொத்த எடை',
    estimatedValue: 'மதிப்பிடப்பட்ட மதிப்பு',
    loanEligibility: 'கடன் தகுதி (75%)',
    generatePreview: 'AI மாதிரிக்காட்சி உருவாக்கவும்',
    loanPreview: 'கடன் மாதிரிக்காட்சி',
  },
  common: {
    logout: 'வெளியேறு',
    name: 'பெயர்',
    phone: 'தொலைபேசி எண்',
    address: 'முகவரி',
    active: 'செயலில்',
    closed: 'மூடப்பட்டது',
    auctioned: 'ஏலம் விடப்பட்டது',
  },
  sidebar: {
    dashboard: 'டாஷ்போர்டு',
    createLoan: 'புதிய கடன்',
    allLoans: 'அனைத்து கடன்கள்',
    renewals: 'புதுப்பித்தல்கள்',
    repayments: 'திருப்பிச் செலுத்துதல்',
    auctions: 'ஏலங்கள்',
    closures: 'மூடல்கள்',
  }
};
